import turtle
import time

hi = turtle.Turtle()
hi.color("blue")
s = turtle.Screen()
s.bgcolor("black")
hi.width(5)
hi.speed(1)
hi.hideturtle()
###########A#################
hi.color("white")
hi.up()
hi.goto(-490, -50)
hi.down()
hi.setheading(70)
hi.fd(200)
hi.bk(100)
hi.setheading(360)
hi.fd(69)
hi.setheading(110)
hi.fd(100)
hi.bk(200)

#################
#hi.color("red")
hi.up()
hi.setheading(360)
hi.goto(-240, 35)
hi.circle(50, 90)
hi.down()
hi.circle(45, 270)
hi.circle(-45, 270)

########################
#hi.color("yellow")
hi.up()
hi.goto(-70, -40)
hi.setheading(360)
hi.down()
hi.circle(35, 90)
hi.fd(100)
hi.circle(35, 180)
hi.fd(100)
hi.circle(35, 90)

#########################
hi.up()
#hi.color("blue")
hi.goto(30, -40)
hi.setheading(90)
hi.down()
hi.fd(170)
hi.bk(85)
hi.setheading(45)
hi.fd(120)
hi.bk(120)
hi.setheading(315)
hi.fd(120)

#######################
#hi.color("green")
hi.up()
hi.setheading(360)
hi.goto(170, -40)
hi.down()
hi.setheading(70)
hi.fd(180)
hi.bk(90)
hi.setheading(360)
hi.fd(65)
hi.setheading(110)
hi.fd(90)
hi.bk(180)

######################

#hi.color("red")
hi.up()
hi.goto(350, -40)
hi.down()
hi.setheading(90)
hi.fd(170)
hi.setheading(300)
hi.fd(200)
hi.setheading(90)
hi.fd(170)




#####################
hi.width(15)
hi.color("blue")
hi.up()
hi.goto(-500, -50)
hi.down()
hi.setheading(70)
hi.fd(200)
hi.bk(100)
hi.setheading(360)
hi.fd(69)
hi.setheading(110)
hi.fd(100)
hi.bk(200)

#################
hi.color("red")
hi.up()
hi.setheading(360)
hi.goto(-250, 35)
hi.circle(50, 90)
hi.down()
hi.circle(45, 270)
hi.circle(-45, 270)

########################
hi.color("yellow")
hi.up()
hi.goto(-80, -40)
hi.setheading(360)
hi.down()
hi.circle(35, 90)
hi.fd(100)
hi.circle(35, 180)
hi.fd(100)
hi.circle(35, 90)

#########################
hi.up()
hi.color("blue")
hi.goto(40, -40)
hi.setheading(90)
hi.down()
hi.fd(170)
hi.bk(85)
hi.setheading(45)
hi.fd(120)
hi.bk(120)
hi.setheading(315)
hi.fd(120)

#######################
hi.color("green")
hi.up()
hi.setheading(360)
hi.goto(180, -40)
hi.down()
hi.setheading(70)
hi.fd(180)
hi.bk(90)
hi.setheading(360)
hi.fd(65)
hi.setheading(110)
hi.fd(90)
hi.bk(180)

######################

hi.color("red")
hi.up()
hi.goto(360, -40)
hi.down()
hi.setheading(90)
hi.fd(170)
hi.setheading(300)
hi.fd(200)
hi.setheading(90)
hi.fd(170)

########################

hi.width(5)
hi.up()
hi.goto(-520, -100)
hi.down()
hi.setheading(360)
hi.color("blue")
hi.fd(167)
hi.color("red")
hi.fd(167)
hi.color("yellow")
hi.fd(167)
hi.color("blue")
hi.fd(167)
hi.color("green")
hi.fd(170)
hi.color("red")
hi.fd(167)

hi.width(5)
hi.up()
hi.goto(-520, -110)
hi.down()
hi.setheading(360)
hi.color("blue")
hi.fd(167)
hi.color("red")
hi.fd(167)
hi.color("yellow")
hi.fd(167)
hi.color("blue")
hi.fd(167)
hi.color("green")
hi.fd(170)
hi.color("red")
hi.fd(167)
#######################

hi.color("yellow")
hi.setheading(360)
hi.up()
hi.goto(0,-300)
hi.down()
hi.circle(80)

hi.fillcolor("yellow")
hi.begin_fill()
hi.setheading(360)
hi.up()
hi.goto(0,-300)
hi.down()
hi.circle(80)
hi.end_fill()
hi.up()
hi.goto(-29, -200)
hi.down()
hi.fillcolor("black")
hi.begin_fill()
hi.circle(12)
hi.end_fill()

hi.goto(29, -200)
hi.down()
hi.fillcolor("black")
hi.begin_fill()
hi.circle(12)
hi.end_fill()

hi.width(10)
hi.goto(0, -280)
hi.down()
#hi.fillcolor("black")
#hi.begin_fill()
hi.color('BLACK')
hi.circle(50, 80)
hi.up()
hi.circle(50, 200)
hi.down()
hi.circle(50, 80)


######################
hi.speed(0)
hi.up()
hi.goto(-400, 250)
hi.down()
hi.speed(1)

hi.color("orange")
hi.write("#Knowledgable", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("blue")
hi.write("#Generous", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("cyan")
hi.write("#Thought_Provoking", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("lightgreen")
hi.write("#Honest", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("gold")
hi.write("#Determined", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("purple")
hi.write("#Intelligent", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("grey")
hi.write("#Well_Organised", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("magenta")
hi.write("#Unbiased", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("red")
hi.write("#Motivating", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("white")
hi.write("#Optimistic", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("orange")
hi.write("#Serious_For_Us", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("skyblue")
hi.write("#Wise", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.color("yellow")
hi.write("#Thank_You", move=True, font=("Verdana", 30, "normal"))

time.sleep(3)

turtle.done()