import turtle
import time
hi = turtle.Turtle()
hi.color("blue")
s = turtle.Screen()
s.bgcolor("black")
hi.width(5)
hi.speed(10)
hi.hideturtle()
############################
def H(x: int, y: int):
    hi.color("blue")
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(90)
    hi.bk(100)
    hi.fd(50)
    hi.setheading(360)
    hi.fd(50)
    hi.setheading(90)
    hi.fd(50)
    hi.bk(100)

def a(x: int, y: int):
    hi.up()
    hi.goto(x, y);
    hi.down()
    hi.circle(-24, 180)
    hi.setheading(270)
    hi.fd(40)
    hi.circle(10, 90)
    hi.up()
    hi.goto(x + 48, y)
    hi.down()
    hi.setheading(210)
    hi.fd(20)
    hi.circle(45, 70)
    hi.setheading(354)
    hi.circle(80, 32)

def p(x: int, y:int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(270)
    hi.fd(100)
    hi.bk(70)
    hi.setheading(360)
    hi.circle(-30, 180)

def A(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(70)
    hi.fd(100)
    hi.bk(50)
    hi.setheading(360)
    hi.fd(34)
    hi.setheading(110)
    hi.fd(50)
    hi.bk(100)

def P(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.setheading(90)
    hi.down()
    hi.fd(80)
    hi.circle(-20, 180)
    hi.fd(20)
    hi.circle(-20, 180)

def Y(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.setheading(300)
    hi.down()
    hi.fd(60)
    hi.setheading(60)
    hi.fd(50)
    hi.bk(100)
    
def T(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(360)
    hi.forward(80)
    hi.bk(40)
    hi.setheading(270)
    hi.forward(100)

def E(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(180)
    hi.fd(50)
    hi.setheading(270)
    hi.fd(100)
    hi.setheading(360)
    hi.fd(50)
    hi.up()
    hi.goto(x - 50, y-50)
    hi.down()
    hi.setheading(360)
    hi.fd(50)

def C(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(90)
    hi.circle(30, 180)
    hi.fd(50)
    hi.circle(30, 180)


def R(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.setheading(90)
    hi.down()
    hi.fd(90)
    hi.circle(-25, 180)
    hi.fd(25)
    hi.circle(-25, 170)
    hi.setheading(315)
    hi.fd(90)

def S(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(90)
    hi.circle(30, 270)
    hi.circle(-30, 270)

def comma(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(270)
    hi.fd(20)
    hi.circle(-10, 80)

def D(x: int, y: int):
    hi.up()
    hi.goto(x, y)
    hi.down()
    hi.setheading(90)
    hi.fd(100)
    hi.setheading(360)
    hi.circle(-50, 90)
    hi.circle(-50, 90)
   



hi.width(20)
hi.color("blue")
H(-480, 300)
hi.color("red")
A(-380, 200)
hi.color("yellow")
P(-280, 200)
hi.color("blue")
P(-190, 200)
hi.color("green")
Y(-100, 300)
hi.color("red")
T(-280, 150)
hi.color("blue")
E(-120, 150)
hi.color("red")
A(-80, 50)
hi.color("yellow")
C(80, 130)
hi.color("blue")
H(130, 150)
hi.color("green")
E(280, 150)
hi.color("red")
R(320, 50)
hi.color("blue")
S(480, 130)
hi.color("yellow")
comma(530, 160)
hi.color("yellow")
D(130, -100)
hi.color("blue")
A(220, -100)
hi.color("green")
Y(320, -10)

hi.speed(5)
hi.up()
hi.goto(-550, -250)
hi.down()
hi.color("Blue")
hi.write("Master", move=False, font=("Verdana", 60, "normal"))
#hi.undo()
hi.up()
hi.goto(-240, -250)
hi.down()
hi.color("yellow")
hi.write("Shifu", move=False, font=("Verdana", 60, "normal"))

hi.up()
hi.goto(0, -250)
hi.down()
hi.color("red")
hi.write("Asokan", move=False, font=("italic", 60, "normal"))

hi.width(5)
hi.color("green")
hi.up()
hi.goto(-560, -250)
hi.down()
hi.setheading(360)
hi.fd(850)
hi.width(5)
hi.color("green")
hi.up()
hi.goto(-560, -260)
hi.down()
hi.setheading(360)
hi.fd(850)
#hi.undo()
#######################
#hi.width(10)
#hi.color("yellow")
#hi.up()
#hi.goto(400, -150)
#hi.down()
#hi.begin_fill()
#hi.circle(5)
#hi.end_fill()

#hi.up()
#hi.goto(450, -150)
#hi.down()
#hi.begin_fill()
#hi.circle(5)
#hi.end_fill()

#hi.up()
#hi.goto(400, -250)
#hi.down()
#hi.setheading(340)
#hi.circle(120, 50)


#hi.speed(0.5)
#hi.color("yellow")
#hi.setheading(360)
#hi.up()
#hi.goto(400,-300)
#hi.down()
#hi.circle(80)

#########  SMILY  ################
hi.speed(10)
hi.color("yellow")
hi.fillcolor("yellow")
hi.begin_fill()
hi.setheading(360)
hi.up()
hi.goto(400,-300)
hi.down()
hi.circle(80)
hi.end_fill()
hi.up()
hi.goto(429, -200)
hi.down()
hi.fillcolor("black")
hi.begin_fill()
hi.circle(10)
hi.end_fill()

hi.goto(370, -200)
hi.down()
hi.fillcolor("black")
hi.begin_fill()
hi.circle(10)
hi.end_fill()

hi.goto(400, -280)
hi.down()
hi.color('BLACK')
hi.circle(50, 80)
hi.up()
hi.circle(50, 200)
hi.down()
hi.circle(50, 80)

#######################

turtle.done()