import turtle
hi = turtle.Turtle()
hi.color("orange")
s = turtle.Screen()
hi.speed(0.4)
s.bgcolor("black")
hi.width(10)
hi.up()
hi.goto(-440,200)
hi.down()
hi.setheading(270)
hi.fd(180)
hi.setheading(300)
hi.circle(80, 120)
hi.setheading(90)
hi.fd(180)

########################
hi.up()
hi.goto(-200, 200)
hi.down()
hi.setheading(360)
hi.forward(150)
hi.setheading(240)
hi.forward(250)
hi.setheading(360)
hi.forward(150)

##########################
hi.up()
hi.goto(30, -15)
hi.setheading(90)
hi.down()
hi.fd(220)
hi.setheading(310)
hi.fd(150)
hi.setheading(60)
hi.fd(140)
hi.setheading(270)
hi.fd(230)

########################
hi.up()
hi.goto(350, 200)
hi.down()
hi.setheading(250)
hi.forward(230)
hi.bk(115)
hi.setheading(360)
hi.forward(100)
hi.setheading(118)
hi.forward(125)
hi.bk(220)

############################
#s.bgcolor("black")
#hi.color("red")
#hi.up()
#hi.goto(-440, -45)
#hi.down()
#hi.setheading(335)
#hi.circle(1050, 55)
#hi.setheading(210)
#hi.circle(-1000, 20)
#hi.setheading(300)
#
#hi.color("red")
#hi.up()
#hi.goto(-440, -40)
#hi.down()
#hi.setheading(335)
#hi.circle(1050, 55)
#hi.setheading(210)
#hi.circle(-1000, 20)
#hi.setheading(300)
#
#hi.color("red")
#hi.up()
#hi.goto(-440, -35)
#hi.down()
#hi.setheading(335)
#hi.circle(1050, 55)
#hi.setheading(210)
#hi.circle(-1000, 20)
#hi.setheading(300)

######################

#s.bgcolor("black")
#hi.fillcolor("red")
#hi.begin_fill()
#hi.circle(190,60)
#hi.circle(50,170)
#hi.circle(890, 7)
#hi.end_fill()
hi.width(4)

s.bgcolor("black")
hi.color("red")
hi.speed(0.4)
hi.up()
hi.goto(-450, -35)
hi.down()
hi.setheading(335)
hi.circle(1000, 55)
hi.setheading(210)
hi.circle(-1000, 20)
hi.setheading(300)

hi.color("red")
hi.up()
hi.goto(-450, -30)
hi.down()
hi.setheading(335)
hi.circle(1000, 55)
hi.setheading(210)
hi.circle(-1000, 20)
hi.setheading(300)

hi.color("red")
hi.up()
hi.goto(-450, -25)
hi.down()
hi.setheading(335)
hi.circle(1000, 55)
hi.setheading(210)
hi.circle(-1000, 20)
hi.setheading(300)

######################

#s.bgcolor("black")
#hi.fillcolor("red")
#hi.speed(0.4)
#hi.begin_fill()
#hi.circle(190,60)
#hi.circle(50,170)
#hi.circle(890, 7)
#hi.end_fill()

#hi.color("orange")
#s = turtle.Screen()
#hi.speed(0.4)
#s.bgcolor("black")
#hi.up()
#hi.goto(300,-230)
#hi.down()
#hi.circle(100)
#
#######################

hi.color("yellow")
hi.up()
hi.setheading(20)
hi.goto(-400, 230)
hi.speed(0.8)
hi.down()
hi.write("HappY BiRThdAy ^_^", move=True, font=("Verdana", 30, "normal"))

######################

hi.color("violet")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(-500, -230)
hi.speed(0.8)
hi.down()
hi.write("#treatYourself", move=True, font=("Verdana", 30, "normal"))


##########################
hi.color("cyan")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, -230)
hi.speed(0.8)
hi.down()
hi.write("#haveAGoodOne", move=True, font=("Verdana", 30, "normal"))


##########################
hi.speed(0.5)
hi.color("yellow")
hi.setheading(360)
hi.up()
hi.goto(0,-300)
hi.down()
hi.circle(80)



hi.fillcolor("yellow")
hi.begin_fill()
hi.setheading(360)
hi.up()
hi.goto(0,-300)
hi.down()
hi.circle(80)
hi.end_fill()
hi.up()
hi.goto(-29, -200)
hi.down()
hi.fillcolor("black")
hi.begin_fill()
hi.circle(12)
hi.end_fill()

hi.goto(29, -200)
hi.down()
hi.fillcolor("black")
hi.begin_fill()
hi.circle(12)
hi.end_fill()

hi.goto(0, -280)
hi.down()
#hi.fillcolor("black")
#hi.begin_fill()
hi.hideturtle()
hi.color('BLACK')
hi.speed(0.8)
hi.circle(50, 80)
hi.speed(0.3)
hi.up()
hi.circle(50, 200)
hi.down()
hi.speed(0.8)
hi.circle(50, 80)
#hi.up()
#hi.goto(0, -270)
#hi.down()
#hi.circle(50, 80)

#hi.up()
#hi.circle(50, 200)
#hi.down()
#hi.circle(50, 80)

hi.up()
hi.goto(32, -195)
hi.down()
hi.hideturtle()
hi.up()
hi.goto(32, -195)
hi.down()
hi.hideturtle()
hi.color("lightgreen")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, 230)
hi.speed(0.6)
hi.down()
hi.write("#Friends", move=True, font=("Verdana", 30, "normal"))
hi.undo()

##########################
hi.color("skyblue")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, 230)
hi.speed(0.6)
hi.down()
hi.write("#Helpful", move=True, font=("Verdana", 30, "normal"))
hi.undo()

##########################
hi.color("white")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, 230)
hi.speed(0.6)
hi.down()
hi.write("#Telepathy", move=True, font=("Verdana", 30, "normal"))
hi.undo()

##########################
hi.color("turquoise")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, 230)
hi.speed(0.6)
hi.down()
hi.write("#Generosity", move=True, font=("Verdana", 30, "normal"))
hi.undo()

##########################
hi.color("green")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, 230)
hi.speed(0.6)
hi.down()
hi.write("#Trust", move=True, font=("Verdana", 30, "normal"))
hi.undo()

##########################
hi.color("magenta")
hi.speed(0)
hi.up()
hi.setheading(20)
hi.goto(200, 230)
hi.speed(0.6)
hi.down()
hi.write("#FriendsForever", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.clear()
hi.up()
hi.goto(-300,100)
hi.down()
hi.speed(1)
hi.write("Thanks for always being with me... :)", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.up()
hi.goto(-250,0)
hi.down()
hi.speed(1)
hi.write("Always be happy :-)", move=True, font=("Verdana", 30, "normal"))
hi.undo()

hi.up()
hi.goto(-200,-100)
hi.down()
hi.speed(1)
hi.write("Best wishes of the day...", move=True, font=("Verdana", 30, "normal"))
hi.undo()

turtle.done()